#!/usr/bin/env python
import argparse
import sqlite3
import sys
import os
from birthday_show import birthday_show


CAPTCHA_LENGTH = 3


def constrain_str(s: str):
    return s


def main():
    top_parser = argparse.ArgumentParser(
        description='Manage birthdays of your friends.',
        add_help=False)
    subparsers = top_parser.add_subparsers(
        title='Available subcommands',
        metavar='subcommand')

    parser_show = subparsers.add_parser('show',
        help='show records',
        description='Show records with filtering constrains.',
        add_help=False)
    parser_show.add_argument('constrain', type=str, nargs='*', help='available constrains: year, age, month, day, name, next, all')
    parser_show.set_defaults(func=birthday_show)

    try:
        args = top_parser.parse_args()
        if not hasattr(args, 'func'):
            top_parser.print_help()
            exit(1)

        args.func(args)
    except KeyboardInterrupt:
        exit(1)


if __name__ == '__main__':
    main()
