#!/usr/bin/env python
import argparse
import sqlite3
import sys
import os
import re

import show
import add


def main():
    top_parser = argparse.ArgumentParser(
        description='Manage birthdays of your friends.',
        add_help=False)
    subparsers = top_parser.add_subparsers(
        title='Available subcommands',
        metavar='subcommand')

    # birthday show
    parser_show = subparsers.add_parser('show',
        help='Show records with filtering constrains.',
        add_help=False)
    parser_show.add_argument('constrains',
        type=show.constrain_str,
        nargs='*', help='available constrains: year, age, month, day, name, next')
    parser_show.set_defaults(func=show.command)

    # birthday add
    parser_add = subparsers.add_parser('add',
        help='Add new record with partial informations',
        add_help=False)
    parser_add.add_argument('name', type=str, help='the name of your friend')
    parser_add.add_argument('date', type=add.date_str, help='birthday of your friend, in xxxx/xx/xx format')
    parser_add.set_defaults(func=add.command)

    try:
        args = top_parser.parse_args()
        if not hasattr(args, 'func'):
            top_parser.print_help()
            exit(1)

        args.func(args)
    except KeyboardInterrupt:
        exit(1)


if __name__ == '__main__':
    main()
